### ISSUE TITLE
Added songs missing in Smash>Select Music Playlist

### ISSUE THREAD

**Issue by Demonslayerx8** [Deinonychus71/Sma5hMusic#57]
As title says, when selecting a playlist through the smash stages, some songs will not appear at all, but they appear just fine via music playlist test section, just not under the smash's playlist menu.

Example of smash>playlist music selection
![My Great Capture Screenshot 2021-06-23 04-28-33](https://user-images.githubusercontent.com/17195757/123089203-7d64f900-d3db-11eb-937d-4bf08c7387ff.png)

And then there's the Sounds>Playlist Music Selection
![My Great Capture Screenshot 2021-06-23 04-29-16](https://user-images.githubusercontent.com/17195757/123089309-a2596c00-d3db-11eb-973c-18f08e028377.png)

**Comment by Deinonychus71** [comment]
Check whether these songs are in playlists and whether the playlist are associated to a stage. There's probably a hidden mechanic somewhere because there is no flag in the db that controls that as far as I know.

**Comment by Demonslayerx8** [comment]
They are indeed in a playlist, and it's in an original playlist. all the songs are labeled as pokemon series.

**Comment by Deinonychus71** [comment]
You'll have to send me your stuff, because I can't reproduce this issue

**Comment by Deinonychus71** [comment]
The issue was troubleshooted. Turns out mods created prior to 1.42 could have lost a couple values after some hashes were cracked.
the following values should be set to "true" (advanced menu)
under PRC DBRoot:
is_selected_original: set to true
is_selected_movie_edit: set to true (optional)

If you edited DLC original songs, it is also possible the following values were altered:
dlc_ui_chara_id
dlc_mii_hat_motif_id
dlc_mii_body_motif_id
If the values aren't there, the easiest way to fix is wipe MusicOverride/core_game_override.json and restart

This is a one time fix. Future songs won't have this issue.

I'll provide a command in software to automatically reapply is_selected_original / is_selected_movie_edit soon

**Comment by Deinonychus71** [comment]
Fix in upcoming 1.52
